Repository dart-code-checker/dart-code-metrics, pull requests merged in 2021-05, with the labels that each got.

#308 Backport member ordering rule
  CHANGELOG.md
  README.md
  doc/rules/member_ordering_extended.md
  lib/src/analyzer_plugin/analyzer_plugin.dart
  lib/src/models/file_record.dart
  lib/src/rules/intl_base/intl_base_visitor.dart
  lib/src/rules/member_ordering_extended/config_parser.dart
  lib/src/rules/member_ordering_extended/member_ordering_extended_rule.dart
  lib/src/rules/member_ordering_extended/models/annotation.dart
  lib/src/rules/member_ordering_extended/models/field_keyword.dart
  lib/src/rules/member_ordering_extended/models/member_group.dart
  lib/src/rules/member_ordering_extended/models/member_type.dart
  lib/src/rules/member_ordering_extended/models/modifier.dart
  lib/src/rules_factory.dart
  test/rules/member_ordering_extended/examples/alphabetical_example.dart
  test/rules/member_ordering_extended/examples/example.dart
  test/rules/member_ordering_extended/examples/multiple_classes_example.dart
  test/rules/member_ordering_extended/member_ordering_extened_rule_test.dart
Labels: enhancement

#310 Support getters in avoid-returning-widgets rule
  CHANGELOG.md
  lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/visitor.dart
  test/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/avoid_returning_widgets_test.dart
  test/analyzers/lint_analyzer/rules/rules_list/avoid_returning_widgets/examples/example.dart
Labels: enhancement

#309 feat: backport avoid returning widgets rule
  CHANGELOG.md
  README.md
  doc/rules/avoid_returning_widgets.md
  lib/src/rules/avoid_preserve_whitespace_false.dart
  lib/src/rules/avoid_returning_widgets_rule.dart
  lib/src/rules/avoid_unused_parameters.dart
  lib/src/rules/binary_expression_operand_order_rule.dart
  lib/src/rules/component_annotation_arguments_ordering.dart
  lib/src/rules/double_literal_format_rule.dart
  lib/src/rules/member_ordering.dart
  lib/src/rules/newline_before_return.dart
  lib/src/rules/no_boolean_literal_compare_rule.dart
  lib/src/rules/no_empty_block.dart
  lib/src/rules/no_equal_arguments.dart
  lib/src/rules/no_equal_then_else.dart
  lib/src/rules/no_magic_number_rule.dart
  lib/src/rules/no_object_declaration.dart
  lib/src/rules/potential_null_dereference.dart
  lib/src/rules/prefer_conditional_expressions.dart
  lib/src/rules/prefer_intl_name.dart
  lib/src/rules/prefer_on_push_cd_strategy.dart
  lib/src/rules/prefer_trailing_comma.dart
  lib/src/rules/prefer_trailing_comma_for_collection.dart
  lib/src/rules/provide_correct_intl_args.dart
  lib/src/rules_factory.dart
  test/rules/avoid_returning_widgets/avoid_returning_widgets_test.dart
  test/rules/avoid_returning_widgets/examples/example.dart
Labels: enhancement

#319 fix: remove unnecessary scan by `lines-of-executable-code`
  .vscode/settings.json
  CHANGELOG.md
  README.md
  lib/src/analyzers/lint_analyzer/metrics_analyzer.dart
  pubspec.yaml
Labels: bug

#318 Doc update
  README.md
  doc/anti-patterns/long-method.md
  doc/metrics/cyclomatic-complexity.md
  doc/metrics/lines-of-code.md
  doc/metrics/maximum-nesting-level.md
  doc/metrics/number-of-methods.md
  doc/metrics/number-of-parameters.md
  doc/metrics/source-lines-of-code.md
  doc/metrics/weight-of-class.md
  doc/rules/avoid-returning-widgets.md
  doc/rules/member-ordering-extended.md
Labels: documentation

#320 Remove lines of executable code
  CHANGELOG.md
  README.md
  bin/metrics.dart
  doc/metrics/lines-of-executable-code.md
  example/example.dart
  lib/metrics_analyzer.dart
  lib/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_method.dart
  lib/src/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_parameter_list.dart
  lib/src/analyzers/lint_analyzer/constants.dart
  lib/src/analyzers/lint_analyzer/lint_analyzer.dart
  lib/src/analyzers/lint_analyzer/reporters/models/file_metrics_report.dart
  lib/src/analyzers/lint_analyzer/reporters/models/function_metrics_report.dart
  lib/src/analyzers/lint_analyzer/reporters/reporters_list/console/lint_console_reporter.dart
  lib/src/analyzers/lint_analyzer/reporters/reporters_list/html/lint_html_reporter.dart
  lib/src/analyzers/lint_analyzer/reporters/reporters_list/html/utility_functions.dart
  lib/src/analyzers/lint_analyzer/reporters/utility_selector.dart
  lib/src/cli/arguments_parser.dart
  lib/src/config_builder/models/deprecated_option.dart
  test/analyzers/lint_analyzer/anti_patterns/anti_patterns_list/long_method/long_method_test.dart
  test/analyzers/lint_analyzer/lint_analyzer_test.dart
  test/analyzers/lint_analyzer/reporters/reporters_list/html/utility_functions_test.dart
  test/analyzers/lint_analyzer/reporters/reporters_list/lint_console_reporter_test.dart
  test/analyzers/lint_analyzer/reporters/utility_selector_test.dart
  test/cli/arguments_parser_test.dart
  test/stubs_builders.dart
Labels: enhancement

#347 Support all variables for no magic number instead of only constants
  CHANGELOG.md
  doc/rules/no-magic-number.md
  lib/src/analyzers/lint_analyzer/rules/rules_list/no_magic_number/no_magic_number.dart
  test/analyzers/lint_analyzer/rules/rules_list/no_magic_number/examples/exceptions_example.dart
Labels: enhancement

#349 feat: support ignored parameters for no equal arguments
  CHANGELOG.md
  README.md
  doc/rules/no-equal-arguments.md
  lib/src/analyzers/lint_analyzer/rules/rules_list/no_equal_arguments/config_parser.dart
  lib/src/analyzers/lint_analyzer/rules/rules_list/no_equal_arguments/no_equal_arguments.dart
  lib/src/analyzers/lint_analyzer/rules/rules_list/no_equal_arguments/visitor.dart
  test/analyzers/lint_analyzer/rules/rules_list/no_equal_arguments/examples/named_parameters_example.dart
  test/analyzers/lint_analyzer/rules/rules_list/no_equal_arguments/no_equal_arguments_test.dart
Labels: enhancement

#346 feat: add Avoid unnecessary setState
  CHANGELOG.md
  README.md
  doc/rules/avoid-unnecessary-setstate.md
  lib/src/analyzers/lint_analyzer/rules/rules_factory.dart
  lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate.dart
  lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/visitor.dart
  test/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate_test.dart
  test/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/examples/example.dart
  test/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/examples/state_subclass_example.dart
Labels: enhancement

#283 Add always remove listener rule
  CHANGELOG.md
  README.md
  doc/rules/always_remove_listener.md
  lib/src/analyzers/lint_analyzer/rules/rules_factory.dart
  lib/src/analyzers/lint_analyzer/rules/rules_list/always_remove_listener/always_remove_listener.dart
  lib/src/analyzers/lint_analyzer/rules/rules_list/always_remove_listener/visitor.dart
  test/analyzers/lint_analyzer/rules/rules_list/always_remove_listener/always_remove_listener_test.dart
  test/analyzers/lint_analyzer/rules/rules_list/always_remove_listener/examples/example.dart
Labels: enhancement

#365 fix: improve setState detection in inline functions
  lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate.dart
  lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/visitor.dart
  test/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate_test.dart
  test/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/examples/example.dart
Labels: enhancement
