Repository dart-code-checker/dart-code-metrics, pull requests merged in 2022-06, with the labels that each got.

#867 Image google/dart is discontinued
  .gitlab-ci.yml
Labels: area-infrastructure

#864 fix: normalize file paths after extraction from analyzed folder
  CHANGELOG.md
  lib/src/utils/file_utils.dart
  test/src/utils/analyzer_utils_test.dart
Labels: area-core

#868 feat: add new rule `avoid-banned-imports` & modify `prefer-extracting-callbacks` allow short callbacks to exist
  CHANGELOG.md
  lib/src/analyzers/lint_analyzer/rules/rules_factory.dart
  lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_banned_imports/avoid_banned_imports_rule.dart
  lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_banned_imports/utils/config_parser.dart
  lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_banned_imports/visitor.dart
  lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/config_parser.dart
  lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/prefer_extracting_callbacks_rule.dart
  lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/visitor.dart
  test/src/analyzers/lint_analyzer/rules/rules_list/avoid_banned_imports/avoid_banned_imports_rule_test.dart
  test/src/analyzers/lint_analyzer/rules/rules_list/avoid_banned_imports/examples/example.dart
  test/src/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/examples/example_max_line_count.dart
  test/src/analyzers/lint_analyzer/rules/rules_list/prefer_extracting_callbacks/prefer_extracting_callbacks_rule_test.dart
  website/docs/rules/common/avoid-banned-imports.md
  website/docs/rules/flutter/prefer-extracting-callbacks.md
  website/docs/rules/overview.md
Labels: type: enhancement, area-rules

#896 feat: improve checkstyle report, added metrics entries
  CHANGELOG.md
  lib/src/analyzers/lint_analyzer/reporters/reporters_list/checkstyle/lint_checkstyle_reporter.dart
  test/src/analyzers/lint_analyzer/reporters/reporters_list/checkstyle/lint_checkstyle_reporter_test.dart
Labels: area-metrics

#895 fix: correctly handle `-` symbol
  CHANGELOG.md
  lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_commenting_analyzer_ignores/visitor.dart
  test/src/analyzers/lint_analyzer/rules/rules_list/prefer_commenting_analyzer_ignores/examples/example.dart
Labels: area-rules
